pipeline {
    agent any

    tools {nodejs "NodeJS"}

    environment {
        PROJECT_PATH="${env.JENKINS_HOME}/workspace/Pipeline Training 2/testing-strategy-3"
        // PROJECT_PATH="${env.JENKINS_HOME}/workspace/OnBoardingPart3/testing-strategy-3"
        SCRIPTS_PATH="${PROJECT_PATH}/scripts"
        REPORT_PATH="${E2E_PATH}/reports"
        E2E_WEB_PATH="${PROJECT_PATH}/e2e-web"
        DEV="dev"
        ALPHA="alpha"
        PREPROD="preprod"
        PROD="prod"
    }

    stages {
        stage('Build') {
            steps {
                dir("${PROJECT_PATH}") {
                    sh '''
                        cd web
                        npm i
                        npm run start&
                    '''
                }
            }
        }

        stage('Prepare test environment on DEV') {
            steps {
                dir("${PROJECT_PATH}") {
                    sh """
                        cd e2e-web
                        pwd
                        ls
                        npm i
                        npm run test
                        kill $(lsof -t -i:3000)
                    """
                }
            }
            post{
                  success{
                      echo "========TEST DEV SUCCESS========"
                  }
                  failure{
                      echo "========TEST DEV FAILURE========"
                      error("========TEST DEV FAILURE========")
                  }
              }
        }

        stage('Deployment') {
            steps {
                dir("${SCRIPTS_PATH}") {
                    sh """
                    """
                }
            }
            post{
                always {  
                    echo "Stop web"
                    sh "kill \$(lsof -t -i :3000)"

                }
                success{
                    echo "========PROD SUCCESS========"
                }
                failure{
                    echo "========PROD FAILURE========"
                    error("========PROD FAILURE========")
                }
            }
        }
    }
}