pipeline {
    agent any

    tools {nodejs "NodeJS"}

    environment {
        PROJECT_PATH="${env.JENKINS_HOME}/workspace/Pipeline Training 2/testing-strategy-3"
        SCRIPTS_PATH="${PROJECT_PATH}/scripts"
        DEV="dev"
        ALPHA="alpha"
        PREPROD="preprod"
        PROD="prod"
    }

    stages {
        stage('Build') {
           steps {
                dir("${PROJECT_PATH}") {
                    sh """
                        cd web
                        npm i
                        npm run start&
                    """
                }
            }
        }
        stage('Test environment DEV') {
            steps {
                dir("${PROJECT_PATH}") {
                   sh """
                        cd e2e-web
                        npm i
                        npm run test
                        kill $(lsof -t -i:3000)
                    """
                }
            }
        }
        stage('Deployment') {
            steps {
                dir("${SCRIPTS_PATH}") {
                   sh """
                    echo "Deployment"
                    """
                }
            }
        }
    }
}