pipeline {
    agent any

    tools {nodejs "NodeJS"}

    environment {
        PROJECT_PATH="${env.JENKINS_HOME}/workspace/OnBoardingPart3/testing-strategy-3"
        SCRIPTS_PATH="${PROJECT_PATH}/scripts"
        DEV="dev"
        ALPHA="alpha"
        PREPROD="preprod"
        PROD="prod"
    }

    stages {
        stage('Build') {
           steps {
                dir("${PROJECT_PATH}") {
                    sh """
                    cd web
                    npm i
                    npm run build
                    """
                }
            }
        }
        stage('Test environment DEV') {
            steps {
                dir("${PROJECT_PATH}") {
                   sh """
                    cd e2e-web
                    npm i
                    npm run test
                    """
                }
            }
        }
        stage('Deployment') {
            steps {
                dir("${SCRIPTS_PATH}") {
                   sh """
                    echo "Deployment"
                    """
                }
            }
        }
    }
}